e2e

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -1,81 +1,81 @@
-# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
-# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven
-
-# This workflow uses actions that are not certified by GitHub.
-# They are provided by a third-party and are governed by
-# separate terms of service, privacy policy, and support
-# documentation.
-
-name: Java CI with Maven
-
-on:
-  workflow_dispatch:
-  push:
-    branches: [ "main" ]
-  pull_request:
-    branches: [ "main" ]
-
-jobs:
-  build:
-
-    runs-on: ubuntu-latest
-
-    steps:
-      - uses: actions/checkout@v4
-      - name: Set up JDK 21
-        uses: actions/setup-java@v4
-        with:
-          java-version: '21'
-          distribution: 'temurin'
-          cache: maven
-
-      # Docker kurulumu
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v2
-
-      # Docker ağı oluşturuluyor
-      - name: Create Docker network
-        run: |
-          docker network create my_network || true
-
-      # Backend uygulamasını Docker Hub'dan çekme
-      - name: Pull backend app from Docker Hub
-        run: |
-          docker pull mehmetaa/backend:latest
-
-      # Frontend uygulamasını Docker Hub'dan çekme
-      - name: Pull frontend app from Docker Hub
-        run: |
-          docker pull mehmetaa/frontend:latest
-
-      # Backend Docker container'ını çalıştırma
-      - name: Run backend Docker container
-        run: |
-          docker run -d --name backend-app --network my_network -p 5000:5000 mehmetaa/backend:latest
-
-      # Frontend Docker container'ını çalıştırma
-      - name: Run frontend Docker container
-        run: |
-          docker run -d --name frontend-app --network my_network -p 3000:3000 -e REACT_APP_API_URL=http://localhost:5000 mehmetaa/frontend:latest
-
-      # Uygulamanın hazır olmasını bekleme
-      - name: Wait for the apps to be ready
-        run: |
-          while ! curl --silent --fail http://localhost:5000; do
-            echo "Waiting for backend to start..."
-            sleep 10
-          done
-          while ! curl --silent --fail http://localhost:3000; do
-            echo "Waiting for frontend to start..."
-            sleep 10
-          done
-          
-      # Selenium Java testlerini çalıştırma
-      - name: Build with Maven
-        run: mvn clean test
-
-#      - name: Upload artifact
-#        uses: github/artifacts@v1
+## This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
+## For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven
+#
+## This workflow uses actions that are not certified by GitHub.
+## They are provided by a third-party and are governed by
+## separate terms of service, privacy policy, and support
+## documentation.
+#
+#name: Java CI with Maven
+#
+#on:
+#  workflow_dispatch:
+#  push:
+#    branches: [ "main" ]
+#  pull_request:
+#    branches: [ "main" ]
+#
+#jobs:
+#  build:
+#
+#    runs-on: ubuntu-latest
+#
+#    steps:
+#      - uses: actions/checkout@v4
+#      - name: Set up JDK 21
+#        uses: actions/setup-java@v4
 #        with:
-#         name: test-results
-#         path: target/cucumber-html-reports/overview-features.html
+#          java-version: '21'
+#          distribution: 'temurin'
+#          cache: maven
+#
+#      # Docker kurulumu
+#      - name: Set up Docker Buildx
+#        uses: docker/setup-buildx-action@v2
+#
+#      # Docker ağı oluşturuluyor
+#      - name: Create Docker network
+#        run: |
+#          docker network create my_network || true
+#
+#      # Backend uygulamasını Docker Hub'dan çekme
+#      - name: Pull backend app from Docker Hub
+#        run: |
+#          docker pull mehmetaa/backend:latest
+#
+#      # Frontend uygulamasını Docker Hub'dan çekme
+#      - name: Pull frontend app from Docker Hub
+#        run: |
+#          docker pull mehmetaa/frontend:latest
+#
+#      # Backend Docker container'ını çalıştırma
+#      - name: Run backend Docker container
+#        run: |
+#          docker run -d --name backend-app --network my_network -p 5000:5000 mehmetaa/backend:latest
+#
+#      # Frontend Docker container'ını çalıştırma
+#      - name: Run frontend Docker container
+#        run: |
+#          docker run -d --name frontend-app --network my_network -p 3000:3000 -e REACT_APP_API_URL=http://localhost:5000 mehmetaa/frontend:latest
+#
+#      # Uygulamanın hazır olmasını bekleme
+#      - name: Wait for the apps to be ready
+#        run: |
+#          while ! curl --silent --fail http://localhost:5000; do
+#            echo "Waiting for backend to start..."
+#            sleep 10
+#          done
+#          while ! curl --silent --fail http://localhost:3000; do
+#            echo "Waiting for frontend to start..."
+#            sleep 10
+#          done
+#
+#      # Selenium Java testlerini çalıştırma
+#      - name: Build with Maven
+#        run: mvn clean test
+#
+##      - name: Upload artifact
+##        uses: github/artifacts@v1
+##        with:
+##         name: test-results
+##         path: target/cucumber-html-reports/overview-features.html
