e2e

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -28,17 +28,17 @@ jobs:
       - name: Build with Maven
         run: mvn clean install -DskipTests
 
-      # 4. Uygulamanın başlatılmasını bekleme (Backend ve Frontend)
-      - name: Wait for the apps to be ready
-        run: |
-          while ! curl --silent --fail http://localhost:3000; do
-            echo "Waiting for backend to start..."
-            sleep 10
-          done
-          while ! curl --silent --fail http://localhost:3000; do
-            echo "Waiting for frontend to start..."
-            sleep 10
-          done
+#      # 4. Uygulamanın başlatılmasını bekleme (Backend ve Frontend)
+#      - name: Wait for the apps to be ready
+#        run: |
+#          while ! curl --silent --fail http://localhost:3000; do
+#            echo "Waiting for backend to start..."
+#            sleep 10
+#          done
+#          while ! curl --silent --fail http://localhost:3000; do
+#            echo "Waiting for frontend to start..."
+#            sleep 10
+#          done
 
       # 5. Testleri çalıştırma (Selenium ve Cucumber testleri)
       - name: Run Selenium tests with Maven
